### ISSUE TITLE
デフォルトのコントロールを非表示にしたい

### ISSUE THREAD

**Issue by kotet** [kurusugawa-computer/cumo#139]
**新機能の概要**
用途によってはカメラのパラメータをGUIから操作してほしくなかったりする。
Python側からデフォルトのコントロールを非表示にして、カスタムコントロールのみを表示するようにしたい。
可能ならcustomというフォルダ名も出ないようにして、カスタムコントロールが最上位にあるようにしたい

![Screenshot from 2024-07-25 11-49-51](https://github.com/user-attachments/assets/aad03c57-8efe-4513-9ba1-9148b3ddfece)

**Comment by kotet** [comment]
インターフェース案
1. `set_speed_control_visiblity(value: bool)`みたいなメンバを生やす
2. デフォルトのコントロールもカスタムコントロールと同じ枠組みで操作可能にする。cumoを利用している既存のコードを壊さない形でこれを実現するのは難しいけどできると嬉しい

**Comment by kotet** [comment]
そうですね、その上で今までPython側から操作不可能だったデフォルトコントロールを削除できるようにする必要があります。
今のまま統一する案をやるとカメラスピードのコントロールを削除した時に復元できなくなってしまうので、スピードコントロールを追加するメソッドを生やすか、もしくはカメラスピードをPython側から操作するメソッドを生やしてエミュレートできるようにしておきたいです

**Comment by NovanMondon** [comment]
私が確認したところ、コントロールとそれによって動かされるプロパティが同時に生成される関係になっているようでした。
これだと、確かにコントロールの削除に付随してプロパティが消滅してしまいますね……。
コントロールとプロパティを分離して、それぞれ操作できるようにする必要がありそうです。

また、cumoで使用されているdat-gui現在更新されておらず、three.jsもlil-guiに移行しているという情報を聞きました。
https://qiita.com/masato_makino/items/1e66b7e6b5bb69865ff4
互換性はあるとの触れ込みですので、こちらにライブラリを更新してもいいかもしれないと思っています。

**Comment by kotet** [comment]
dat.guiは当時three.jsのライブデモのコントロールで使われがちで手早く作れそうだったというだけで選んだライブラリなので、新しく主流になってるものがあるなら更新してくれてOKです
