### ISSUE TITLE
平行投影モード（？）のときにカメラを平行移動できない

### ISSUE THREAD

**Issue by strshp** [kurusugawa-computer/cumo#14]
**バグの説明**
* 平行投影モードに切り替えたとき (Viewer > camera > perspective のチェックを外す) に、カメラの平行移動が出来なくなる。
![image](https://user-images.githubusercontent.com/44435351/139539425-b26a5593-603f-4fc6-8d11-ab63c5c2af62.png)

**再現手順**
1. Viewer で何らかの点群と Cuboid を表示
2. Viewer 右上にあるコントロールパネルの camera > perspective のチェックを外す
3. マウスの右クリックドラッグでカメラを動かそうとしてみる →動かない

* [simple-kitti-viewer](https://github.com/kurusugawa-computer/simple-kitti-viewer/tree/feature/guild-viewer) でリポジトリ内のテストデータ (testdata/kitti) を表示している時に起こりました。

**補足**
* 投資投影モード (perspective のチェックが入った状態) では、マウスの右クリックでカメラの平行移動が出来ることを確認しました。

**Comment by unarist** [comment]
cumo 0.25.0 でこんな感じでした。

https://github.com/kurusugawa-computer/cumo/assets/705555/9acc7c2f-282c-4518-b3c6-cbd69f2cf908

1. 左ドラッグ（回転する）
2. 右ドラッグ（平行移動する）
3. perspective camera off & めっちゃ小さいので拡大
4. 左ドラッグ（回転する）
5. 右ドラッグ（なんか誤差みたいな動きしかしなくて、平行移動になっているのかよくわからない）
6. 左ドラッグ（回転する）
7. 右ドラッグ（やはりよくわからない）

ソースコードはこれです。

```
import numpy
from cumo import PointCloudViewer


def main():
    host = "127.0.0.1"
    websocket_port = 8091
    http_port = 8092

    viewer = PointCloudViewer(
        host=host, websocket_port=websocket_port, http_port=http_port, autostart=True
    )
    print(f"open: http://{host}:{http_port}")
    print("setup...")

    viewer.remove_all_objects()
    viewer.remove_all_custom_controls()

    points = numpy.array([
        [0, 0, 0],
        [1, 0, 0], [0, 1, 0], [0, 0, 1],
        [1, 1, 0], [1, 0, 1], [0, 1, 1],
        [2, 0, 0], [0, 2, 0], [0, 0, 2]
    ])
    points = points * numpy.ones((3,))*0.1
    points = points.astype("float32")

    lines = numpy.array([[0, 7], [0, 8], [0, 9]]).astype("uint32")
    colors = numpy.array([[255, 0, 0], [0, 255, 0], [0, 0, 255],]).astype("uint8")
    widths = (numpy.ones((3,))*5.0).astype("float32")
    viewer.send_lineset(points, lines, colors, widths)

    triangles = numpy.array([[0, 1, 2], [0, 2, 3], [3, 1, 0]]).astype("uint32")
    colors = numpy.array([[255, 255, 255], [255, 0, 0], [0, 255, 0], [0, 0, 255]]).astype("uint8")
    viewer.send_mesh(points, triangles, colors)

    viewer.wait_forever()


if __name__ == "__main__":
    main()
```

**Comment by kotet** [comment]
babylonjs移行後のバージョンでも遅いですか？

**Comment by kotet** [comment]
現在、上下方向のパンに使う基準が「画面の上端」方向でなくカメラに設定された上のベクトルなので、たとえばロール固定モードで真上を向いた状態で上下方向のパンを行うとほとんど動かない
画面の上方向のベクトルを正しく計算して利用できれば解決するかも
